In [17]:
pip install mlflow optuna xgboost lightgbm

Collecting mlflow
  Downloading mlflow-3.14.0-py3-none-any.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/49.7 kB ? eta -:--:--
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.3.0)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (4.6.0)
Collecting mlflow-skinny==3.14.0 (from mlflow)
  Downloading mlflow_skinny-3.14.0-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 1.6 MB/s eta 0:00:00
Collecting mlflow-tracing==3.14.0 (from mlflow)
  Downloading mlflow_tracing-3.14.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.14.1)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.5)
Collecting cryptography<49,>=43.0.0 (from mlflow)
  Downloading cryptography-48.0.1-cp311-abi3-manylinux_2_34_x86_64.whl.metadata (4.3 kB)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<27 (from mlflow)
  Downloading gunicorn-26.0.0-py3-none-any.whl.metadata (5.4 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Downloading huey-3.2.1-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<25,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.51)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (8.4.2)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.14.0->mlflow)
  Downloading databricks_sdk-0.120.0-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (0.138.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (3.1.50)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (9.0.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (1.42.1)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.14.0->mlflow)
  Downloading opentelemetry_proto-1.43.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (1.42.1)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (26.2)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (2.13.4)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.14.0->mlflow) (0.49.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.7)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.24.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.1.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography<49,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.18.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography<49,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow) (2.49.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.14.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.14.0->mlflow) (0.0.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.14.0->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.14.0->mlflow) (4.1.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.14.0->mlflow) (0.63b1)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.14.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.14.0->mlflow) (2.46.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.14.0->mlflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.14.0->mlflow) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.14.0->mlflow) (2026.6.17)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette<2->mlflow-skinny==3.14.0->mlflow) (4.14.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1->mlflow-skinny==3.14.0->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.14.0->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow) (0.6.3)
Downloading mlflow-3.14.0-py3-none-any.whl (12.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 38.9 MB/s eta 0:00:00
Downloading mlflow_skinny-3.14.0-py3-none-any.whl (3.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 44.9 MB/s eta 0:00:00
Downloading mlflow_tracing-3.14.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 45.6 MB/s eta 0:00:00
Downloading cryptography-48.0.1-cp311-abi3-manylinux_2_34_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 50.8 MB/s eta 0:00:00
Downloading docker-7.2.0-py3-none-any.whl (148 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 5.1 MB/s eta 0:00:00
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 4.0 MB/s eta 0:00:00
Downloading gunicorn-26.0.0-py3-none-any.whl (212 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 9.9 MB/s eta 0:00:00
Downloading huey-3.2.1-py3-none-any.whl (120 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.0/121.0 kB 6.0 MB/s eta 0:00:00
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 6.4 MB/s eta 0:00:00
Downloading databricks_sdk-0.120.0-py3-none-any.whl (954 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.6/954.6 kB 25.9 MB/s eta 0:00:00
Downloading graphql_core-3.2.11-py3-none-any.whl (214 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.9/214.9 kB 13.1 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading opentelemetry_proto-1.43.0-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 4.2 MB/s eta 0:00:00
Installing collected packages: huey, opentelemetry-proto, gunicorn, graphql-core, graphql-relay, docker, cryptography, skops, graphene, Flask-CORS, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow
  Attempting uninstall: cryptography
    Found existing installation: cryptography 49.0.0
    Uninstalling cryptography-49.0.0:
      Successfully uninstalled cryptography-49.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyopenssl 26.3.0 requires cryptography<50,>=49.0.0, but you have cryptography 48.0.1 which is incompatible.
Successfully installed Flask-CORS-6.0.5 cryptography-48.0.1 databricks-sdk-0.120.0 docker-7.2.0 graphene-3.4.3 graphql-core-3.2.11 graphql-relay-3.2.0 gunicorn-26.0.0 huey-3.2.1 mlflow-3.14.0 mlflow-skinny-3.14.0 mlflow-tracing-3.14.0 opentelemetry-proto-1.43.0 skops-0.14.0

In [3]:
xdassxz

NameError: name 'xdassxz' is not defined

In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [26]:
df = pd.read_csv("data/student_success_features.csv",encoding="utf-8")
df.head()

,student_presentation_id,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,disability,...,n_assessments_submitted,weighted_avg_score,avg_score,n_late_submissions,n_banked_assessments,n_active_days,total_clicks,n_distinct_materials_accessed,final_result,label_pass
0,AAA-2013J-11391,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,N,...,5,82.4,82.0,0,0,40,934,55,Pass,1
1,AAA-2013J-28400,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,N,...,5,65.4,66.4,2,0,80,1435,84,Pass,1
2,AAA-2013J-31604,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,N,...,5,76.3,76.0,0,0,123,2158,82,Pass,1
3,AAA-2013J-32885,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,N,...,5,55.0,54.4,5,0,70,1034,66,Pass,1
4,AAA-2013J-38053,AAA,2013J,38053,M,Wales,A Level or Equivalent,80-90%,35-55,N,...,5,66.9,68.0,1,0,143,2445,88,Pass,1

 Evaluations soumises ➡️ n_assessments_submitted🗓️ jour d'activite ➡️ n_active_days📚 Supports consultes ➡️ n_distinct_materials_accessed🖱️ Total clics ➡️ total_clicks📈 Note ponderee moyenne ➡️ weighted_avg_score📝 Note moyenne ➡️ avg_score⏳ Soumissions tardives ➡️ n_late_submissions

In [27]:
X = df[["n_assessments_submitted","n_active_days",
       "total_clicks","weighted_avg_score","avg_score","n_late_submissions"]]
y = df["label_pass"]

In [8]:
X.head()

,n_assessments_submitted,n_active_days,total_clicks,weighted_avg_score,avg_score,n_late_submissions
0,5,40,934,82.4,82.0,0
1,5,80,1435,65.4,66.4,2
2,5,123,2158,76.3,76.0,0
3,5,70,1034,55.0,54.4,5
4,5,143,2445,66.9,68.0,1

In [14]:
y.unique()

array([1, 0])

In [4]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=42,stratify=y)

In [12]:
import requests
import mlflow

# 1. تحديد الرابط الصحيح لشبكة دوكر
MLFLOW_URI = "http://mlflow:5000"
mlflow.set_tracking_uri(MLFLOW_URI)

print("1. Testing network connection to MLflow container...")
try:
    # محاولة الاتصال المباشر بالسيرفر للاطمئنان على الشبكة
    response = requests.get(f"{MLFLOW_URI}/health", timeout=5)
    print(f"   -> Network Status Code: {response.status_code} (Success!)")
except Exception as e:
    print(f"   -> Network Connection Failed! Error: {e}")

print("\n2. Testing MLflow Client API...")
try:
    # محاولة الاتصال عبر مكتبة mlflow وإنشاء تجربة وهمية للاختبار
    mlflow.set_experiment("Test_Connection_Experiment")
    
    with mlflow.start_run(run_name="Test_Run"):
        mlflow.log_param("status", "connected")
        mlflow.log_metric("test_metric", 1.0)
        
    print("   -> MLflow integration is working perfectly! Check your MLflow UI now.")
except Exception as e:
    print(f"   -> MLflow API Failed! Error: {e}")

2026/07/10 21:14:08 INFO mlflow.tracking.fluent: Experiment with name 'Test_Connection_Experiment' does not exist. Creating a new experiment.

1. Testing network connection to MLflow container...
   -> Network Status Code: 200 (Success!)

2. Testing MLflow Client API...
🏃 View run Test_Run at: http://mlflow:5000/#/experiments/2/runs/fa3380e166554df4b060e3f1b9678610
🧪 View experiment at: http://mlflow:5000/#/experiments/2
   -> MLflow integration is working perfectly! Check your MLflow UI now.

In [5]:
import warnings
warnings.filterwarnings("ignore")

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score
import mlflow
import optuna

mlflow.set_experiment("All_Models_ExperimentV")
mlflow.set_tracking_uri("http://mlflow:5000")

2026/07/10 21:14:48 INFO mlflow.tracking.fluent: Experiment with name 'All_Models_ExperimentV' does not exist. Creating a new experiment.

In [14]:

def objective(trial):
    # Choose classifier
    classifier_name = trial.suggest_categorical(
        "classifier", ["LogisticRegression", "RandomForest", "XGBClassifier", "LGBMClassifier"]
    )

    # Define parameters based on selection
    if classifier_name == "LogisticRegression":
        c_val = trial.suggest_float("lr_c", 1e-3, 10, log=True)
        clf = LogisticRegression(C=c_val, random_state=42, max_iter=1000)

    elif classifier_name == "RandomForest":
        n_estimators = trial.suggest_int("rf_n_estimators", 50, 300)
        max_depth = trial.suggest_int("rf_max_depth", 3, 15)
        clf = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, random_state=42)

    elif classifier_name == "XGBClassifier":
        n_estimators = trial.suggest_int("xgb_n_estimators", 50, 300)
        max_depth = trial.suggest_int("xgb_max_depth", 3, 10)
        learning_rate = trial.suggest_float("xgb_lr", 1e-3, 0.3, log=True)
        clf = XGBClassifier(n_estimators=n_estimators, max_depth=max_depth, learning_rate=learning_rate, random_state=42)

    else: # LGBMClassifier
        n_estimators = trial.suggest_int("lgbm_n_estimators", 50, 300)
        num_leaves = trial.suggest_int("lgbm_num_leaves", 20, 150)
        learning_rate = trial.suggest_float("lgbm_lr", 1e-3, 0.3, log=True)
        clf = LGBMClassifier(n_estimators=n_estimators, num_leaves=num_leaves, learning_rate=learning_rate, random_state=42, verbose=-1)

    # Create a pipeline to handle NaNs automatically
    pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='mean')),
        ('classifier', clf)
    ])

    # Cross-validation on training data
    score = cross_val_score(pipeline, x_train, y_train, cv=3, scoring='accuracy').mean()

    # Log to MLflow
    with mlflow.start_run(run_name=f"Trial_{trial.number}_{classifier_name}", nested=True):
        mlflow.log_param("model_type", classifier_name)
        mlflow.log_params(trial.params)
        mlflow.log_metric("accuracy", score)

    return score

# Run the optimization
study = optuna.create_study(direction="maximize")
with mlflow.start_run(run_name="Main_ML_Search"):
    study.optimize(objective, n_trials=20)

print("Best Trial:", study.best_trial.params)

[I 2026-07-10 21:15:01,642] A new study created in memory with name: no-name-f4aedd08-437f-4dea-95a6-b5d0106f9baa
[I 2026-07-10 21:15:02,475] Trial 0 finished with value: 0.9124413976341587 and parameters: {'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 68, 'lgbm_num_leaves': 40, 'lgbm_lr': 0.13297574415307709}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_0_LGBMClassifier at: http://mlflow:5000/#/experiments/3/runs/675b4836fae24af4acaba4bd8bb8c692
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:11,448] Trial 1 finished with value: 0.9089896170843487 and parameters: {'classifier': 'RandomForest', 'rf_n_estimators': 186, 'rf_max_depth': 11}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_1_RandomForest at: http://mlflow:5000/#/experiments/3/runs/edc3fe22f35147a191502e41c1d356a1
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:12,481] Trial 2 finished with value: 0.9119043863340334 and parameters: {'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 103, 'lgbm_num_leaves': 57, 'lgbm_lr': 0.11781801376766675}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_2_LGBMClassifier at: http://mlflow:5000/#/experiments/3/runs/91d88b9931064494b85de9f9f0ef9996
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:16,033] Trial 3 finished with value: 0.9081842611921017 and parameters: {'classifier': 'RandomForest', 'rf_n_estimators': 74, 'rf_max_depth': 10}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_3_RandomForest at: http://mlflow:5000/#/experiments/3/runs/d548188c4f24438aaf32d53568a17e2c
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:17,901] Trial 4 finished with value: 0.9082609644848443 and parameters: {'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 161, 'lgbm_num_leaves': 135, 'lgbm_lr': 0.004022307075263112}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_4_LGBMClassifier at: http://mlflow:5000/#/experiments/3/runs/f3fbd471178347f48b36802fc9f89898
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:19,307] Trial 5 finished with value: 0.9124030437815142 and parameters: {'classifier': 'XGBClassifier', 'xgb_n_estimators': 109, 'xgb_max_depth': 9, 'xgb_lr': 0.089929007007316}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_5_XGBClassifier at: http://mlflow:5000/#/experiments/3/runs/942bd6f98f214f5b948ad10a74e8a1bd
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:31,927] Trial 6 finished with value: 0.9034669005810424 and parameters: {'classifier': 'RandomForest', 'rf_n_estimators': 296, 'rf_max_depth': 6}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_6_RandomForest at: http://mlflow:5000/#/experiments/3/runs/ea889d9b4634421cbd30ecfa92956c0f
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:33,287] Trial 7 finished with value: 0.8976373973820433 and parameters: {'classifier': 'XGBClassifier', 'xgb_n_estimators': 114, 'xgb_max_depth': 8, 'xgb_lr': 0.0013936484766289398}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_7_XGBClassifier at: http://mlflow:5000/#/experiments/3/runs/a4d11a9b1a774160bc8cbf53eab4de3c
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:34,378] Trial 8 finished with value: 0.8873204581232675 and parameters: {'classifier': 'LogisticRegression', 'lr_c': 0.002248433717738509}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_8_LogisticRegression at: http://mlflow:5000/#/experiments/3/runs/397c9f8430ae459cb411a3ae4e2f7b8e
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:36,169] Trial 9 finished with value: 0.9029684328730535 and parameters: {'classifier': 'XGBClassifier', 'xgb_n_estimators': 157, 'xgb_max_depth': 6, 'xgb_lr': 0.0018893299590696012}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_9_XGBClassifier at: http://mlflow:5000/#/experiments/3/runs/dd4b7d90d2324027998cbc2c10a97507
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:37,347] Trial 10 finished with value: 0.9116359490784388 and parameters: {'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 299, 'lgbm_num_leaves': 25, 'lgbm_lr': 0.09851608051073317}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_10_LGBMClassifier at: http://mlflow:5000/#/experiments/3/runs/476c6b72d0e14bdfbd7089e1ef9db346
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:38,787] Trial 11 finished with value: 0.9094499074415457 and parameters: {'classifier': 'XGBClassifier', 'xgb_n_estimators': 267, 'xgb_max_depth': 3, 'xgb_lr': 0.18338528773496834}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_11_XGBClassifier at: http://mlflow:5000/#/experiments/3/runs/9e74b115c73548fe8fbd97bbdf7d085d
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:39,777] Trial 12 finished with value: 0.8878573855850124 and parameters: {'classifier': 'LogisticRegression', 'lr_c': 7.546612811863}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_12_LogisticRegression at: http://mlflow:5000/#/experiments/3/runs/2f711ab9a0dc48fd96bfffcbaafd48d6
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:40,763] Trial 13 finished with value: 0.9097567515003407 and parameters: {'classifier': 'XGBClassifier', 'xgb_n_estimators': 57, 'xgb_max_depth': 10, 'xgb_lr': 0.250442575636319}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_13_XGBClassifier at: http://mlflow:5000/#/experiments/3/runs/181f6676b8234ae0acf2e7a29918bf5a
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:41,614] Trial 14 finished with value: 0.8094277855818072 and parameters: {'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 60, 'lgbm_num_leaves': 111, 'lgbm_lr': 0.0010842897636821206}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_14_LGBMClassifier at: http://mlflow:5000/#/experiments/3/runs/94e0b0efac8b4973865c464f69d5d1e8
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:47,222] Trial 15 finished with value: 0.9062283117832514 and parameters: {'classifier': 'XGBClassifier', 'xgb_n_estimators': 298, 'xgb_max_depth': 3, 'xgb_lr': 0.031566420898031085}. Best is trial 0 with value: 0.9124413976341587.

🏃 View run Trial_15_XGBClassifier at: http://mlflow:5000/#/experiments/3/runs/2e7dad3207d447e9b2b59cdd1fd6ef7d
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:49,258] Trial 16 finished with value: 0.9132467402887666 and parameters: {'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 237, 'lgbm_num_leaves': 81, 'lgbm_lr': 0.0153769135254327}. Best is trial 16 with value: 0.9132467402887666.

🏃 View run Trial_16_LGBMClassifier at: http://mlflow:5000/#/experiments/3/runs/9ed3f4ec4a2d4b639cb7c0bdb7db2fb0
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:51,103] Trial 17 finished with value: 0.9135918896621965 and parameters: {'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 233, 'lgbm_num_leaves': 78, 'lgbm_lr': 0.018821642010299962}. Best is trial 17 with value: 0.9135918896621965.

🏃 View run Trial_17_LGBMClassifier at: http://mlflow:5000/#/experiments/3/runs/48970211ec5d4f6bb59c65528d2db2fb
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:53,459] Trial 18 finished with value: 0.9136686547305876 and parameters: {'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 244, 'lgbm_num_leaves': 82, 'lgbm_lr': 0.019526218143424607}. Best is trial 18 with value: 0.9136686547305876.

🏃 View run Trial_18_LGBMClassifier at: http://mlflow:5000/#/experiments/3/runs/1ee1d2f1e320482ba3af95119f98669b
🧪 View experiment at: http://mlflow:5000/#/experiments/3

[I 2026-07-10 21:15:55,563] Trial 19 finished with value: 0.9137069953455931 and parameters: {'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 229, 'lgbm_num_leaves': 83, 'lgbm_lr': 0.018430170439382092}. Best is trial 19 with value: 0.9137069953455931.

🏃 View run Trial_19_LGBMClassifier at: http://mlflow:5000/#/experiments/3/runs/dd9fbf744f134eb785cdea15198aeed7
🧪 View experiment at: http://mlflow:5000/#/experiments/3
🏃 View run Main_ML_Search at: http://mlflow:5000/#/experiments/3/runs/fa411abfc91c4c4683b873a01f72c283
🧪 View experiment at: http://mlflow:5000/#/experiments/3
Best Trial: {'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 229, 'lgbm_num_leaves': 83, 'lgbm_lr': 0.018430170439382092}

In [15]:
study.best_trial.model

FrozenTrial(number=19, state=<TrialState.COMPLETE: 1>, values=[0.9137069953455931], datetime_start=datetime.datetime(2026, 7, 10, 21, 15, 53, 460478), datetime_complete=datetime.datetime(2026, 7, 10, 21, 15, 55, 563685), params={'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 229, 'lgbm_num_leaves': 83, 'lgbm_lr': 0.018430170439382092}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'classifier': CategoricalDistribution(choices=('LogisticRegression', 'RandomForest', 'XGBClassifier', 'LGBMClassifier')), 'lgbm_n_estimators': IntDistribution(high=300, log=False, low=50, step=1), 'lgbm_num_leaves': IntDistribution(high=150, log=False, low=20, step=1), 'lgbm_lr': FloatDistribution(high=0.3, log=True, low=0.001, step=None)}, trial_id=19, value=None)

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# 1. طباعة أفضل المعاملات
best_params = study.best_trial.params
print("Best Params:", best_params)

# 2. استخراج اسم أفضل نموذج عثرت عليه الأداة
best_classifier_name = best_params["classifier"]

# 3. بناء النموذج الفائز بناءً على اسمه ومعاملاته
if best_classifier_name == "LogisticRegression":
    clf = LogisticRegression(C=best_params["lr_c"], random_state=42, max_iter=1000)

elif best_classifier_name == "RandomForest":
    clf = RandomForestClassifier(n_estimators=best_params["rf_n_estimators"], max_depth=best_params["rf_max_depth"], random_state=42)

elif best_classifier_name == "XGBClassifier":
    clf = XGBClassifier(n_estimators=best_params["xgb_n_estimators"], max_depth=best_params["xgb_max_depth"], learning_rate=best_params["xgb_lr"], random_state=42)

else: # LGBMClassifier
    clf = LGBMClassifier(n_estimators=best_params["lgbm_n_estimators"], num_leaves=best_params["lgbm_num_leaves"], learning_rate=best_params["lgbm_lr"], random_state=42, verbose=-1)

# 4. إنشاء الـ Pipeline النهائي وتدريبه (Fit)
best_model = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('classifier', clf)
])

# تدريب النموذج الفائز على كامل البيانات
best_model.fit(x_train, y_train)

print("Best model is ready to use!")
# الآن يمكنك استخدام النموذج الفائز للتنبؤ مباشرة: best_model.predict(x_test)

Best Params: {'classifier': 'LGBMClassifier', 'lgbm_n_estimators': 229, 'lgbm_num_leaves': 83, 'lgbm_lr': 0.018430170439382092}
Best model is ready to use!

In [29]:
best_model

Pipeline(steps=[('imputer', SimpleImputer()),
                ('classifier',
                 LGBMClassifier(learning_rate=0.018430170439382092,
                                n_estimators=229, num_leaves=83,
                                random_state=42, verbose=-1))])

In [35]:
best_model.score(x_train,y_train)

0.9359898749712358

In [31]:
import joblib
joblib.dump(best_model,"best_model.joblib")

['best_model.joblib']

In [47]:
from sklearn.metrics import classification_report,classification_reports

ImportError: cannot import name 'classification_reports' from 'sklearn.metrics' (/usr/local/lib/python3.11/site-packages/sklearn/metrics/__init__.py)

In [34]:
import mlflow

mlflow.set_experiment("Test_The_Best_Model")
mlflow.set_registry_uri("http://mlflow:5000")

2026/07/10 21:50:14 INFO mlflow.tracking.fluent: Experiment with name 'Test_The_Best_Model' does not exist. Creating a new experiment.

In [39]:
y_pred =  best_model.predict(x_test)
report = classification_report(y_pred,y_test)
print(report)

              precision    recall  f1-score   support

           0       0.88      0.94      0.91      3225
           1       0.94      0.88      0.91      3294

    accuracy                           0.91      6519
   macro avg       0.91      0.91      0.91      6519
weighted avg       0.91      0.91      0.91      6519

In [50]:
report_dict = classification_report(y_pred,y_test,output_dict=True)
print(report_dict)

{'0': {'precision': 0.8849506101104009, 'recall': 0.9444961240310078, 'f1-score': 0.9137543122843858, 'support': 3225.0}, '1': {'precision': 0.9418264543386415, 'recall': 0.8797814207650273, 'f1-score': 0.9097472924187726, 'support': 3294.0}, 'accuracy': 0.9117962877741985, 'macro avg': {'precision': 0.9133885322245212, 'recall': 0.9121387723980175, 'f1-score': 0.9117508023515792, 'support': 6519.0}, 'weighted avg': {'precision': 0.9136895318603356, 'recall': 0.9117962877741985, 'f1-score': 0.9117295963099527, 'support': 6519.0}}

In [54]:
with mlflow.start_run(run_name="Test_model"):
        mlflow.log_params(best_params)
        mlflow.log_metrics({"Target":"0",
                             "Precision":report_dict["0"]["precision"],
                             "Recall":report_dict["0"]["recall"],
                             "F1-score":report_dict["0"]["f1-score"]})
        mlflow.log_metrics({"Target":"1",
                             "Precision":report_dict["1"]["precision"],
                             "Recall":report_dict["1"]["recall"],
                             "F1-score":report_dict["1"]["f1-score"]})
        mlflow.log_metric("Accuracy",report_dict["accuracy"] )
        # إضافة تاجات متعددة باستخدام قاموس
        mlflow.set_tags({
            "model_type": best_params["classifier"],
            "developer": "Houssame Bouoys",
            "stage": "Hyperparameter_Tuning"
        })

🏃 View run Test_model at: http://mlflow:5000/#/experiments/4/runs/ab5ce275892c45b987bd295d690a31df
🧪 View experiment at: http://mlflow:5000/#/experiments/4